(()=>{
'use strict';
const root=document.getElementById('demo');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const machines=[{id:'MP-001',name:'JCB 540-170',fleet:'TH-042',hirer:'Northbank Plant Hire',site:'Whitmore Road'},{id:'MP-002',name:'JCB 535-140',fleet:'TH-018',hirer:'Northbank Plant Hire',site:'Cromwell Road'},{id:'MP-003',name:'Manitou MT 1440',fleet:'TH-063',hirer:'Northbank Plant Hire',site:'Whitmore Road'}];
const areas=['Tyres & wheels','Fluids & visible leaks','Boom & carriage','Grease points','Cab & controls','Lights & safety systems'];
let user=null,role='operator',page='login',machine=machines[0],site='',recipient='',answers={},note='',photo='',records=[],selected=null,stage=0,email='',signup=false,delivery='',error='';
const destinations={};
function btn(label,action,cls='primary'){return `<button type="button" class="${cls}" data-action="${action}">${label}</button>`}
function go(p){page=p;error='';render();window.scrollTo(0,0);root.querySelector('h1')?.focus({preventScroll:true});}
function shell(content,narrow=false){return `<div class="demo-bar"><span>INTERACTIVE DEMO · No emails sent · Data resets on reload</span>${btn(role==='hirer'?'Try operator':'Try hirer','switch','')}</div><header class="top"><a class="wordmark" href="#" data-action="home"><span>MACHINE</span><span>PRE-CHECK</span></a><nav aria-label="Main navigation">${user?`${btn(role==='hirer'?'Fleet':'Home','home',page==='home'||page==='fleet'?'active':'')}${btn('My records','records',page==='records'?'active':'')}${btn('Sign out','logout','')}`:''}</nav></header><div class="wrap ${narrow?'narrow':''} ${page==='login'?'login':''}">${content}</div>`;}
function recipients(){return `<div class="box"><h3>Who receives this check?</h3><div class="row"><div><strong>You</strong><p class="muted small">${esc(user?.email)}</p></div><span class="badge neutral">Your record</span></div><div class="row"><div><strong>${esc(machine.hirer||'No connected hirer')}</strong><p class="muted small">${machine.hirer?'Inspection & reported defects':'Personal check only'}</p></div></div><div class="row"><div><strong>Site copy</strong><p class="muted small">${recipient?esc(recipient):'No email recipient selected'}</p></div></div></div>`;}
function rows(list){return list.length?list.map(r=>`<div class="row"><div><strong>${esc(r.name)}</strong><p class="muted small">${esc(r.site)} · ${esc(r.time)}</p><span class="badge ${r.defect?'warn':''}">${r.defect?'Defect reported':'No defects reported'}</span></div>${btn('View','record:'+r.id,'ghost')}</div>`).join(''):'<div class="empty">No checks yet. Your first completed check will appear here.</div>';}
function render(){let c='',narrow=false;
if(page==='login'){narrow=true;c=`<h1 tabindex="-1">MACHINE<br>PRE-CHECK</h1><form id="loginForm">${signup?'<label>Your name<input name="name" autocomplete="name" maxlength="80" required></label>':''}<label>Email<input name="email" type="email" autocomplete="email" value="${esc(email)}" required></label><button class="primary">CONTINUE WITH EMAIL</button></form>${btn(signup?'Already have an account? Sign in':'New here? Create your account','signup','text-button')}<div class="privacy">Demo only. Use a made-up email, or ${btn('Continue as Operator K','demo-user','ghost')}</div>`;}
if(page==='verify'){narrow=true;c=`<p class="kicker">Email sign-in</p><h1 tabindex="-1">Check your email.</h1><p class="muted">${esc(email)}</p><div class="status">Demo: no message was sent. Enter <strong>123456</strong> to try the code screen.</div><form id="codeForm"><label>Email code<input name="code" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" required></label><button class="primary">SIGN IN</button></form>${btn('Simulate opening email link','verify','ghost')}${btn('Use a different email','login','text-button')}`;}
if(page==='home'){c=`<p class="kicker">Operator · ${esc(user.name)}</p><h1 tabindex="-1">Ready for your check.</h1><div class="grid"><div><div class="hero-box"><p class="kicker">At the machine</p><h2>Scan. Check. Keep the record.</h2><p>No site account needed.</p>${btn('SCAN MACHINE QR','scan','')}</div>${btn('Machine has no QR? Start a personal check','personal','ghost')}</div><div><h2>Recent checks</h2>${rows(records.slice(0,3))}<p class="privacy">Your account follows you between sites. Site copies go only to the recipient you confirm.</p></div></div>`;}
if(page==='scan'){narrow=true;c=`<p class="kicker">01 / Machine</p><h1 tabindex="-1">Scan the machine.</h1><div class="scan-zone"><strong>Machine QR</strong><p class="muted">Camera scanning is simulated in this prototype.</p>${btn('USE DEMO QR · TH-042','machine:MP-001')}</div><h3>Try another machine</h3>${machines.slice(1).map(m=>`<div class="row"><div><strong>${m.name}</strong><p class="muted small">${m.fleet} · ${m.site}</p></div>${btn('Select','machine:'+m.id,'ghost')}</div>`).join('')}${btn('Back','home','text-button')}`;}
if(page==='personal'){narrow=true;c=`<p class="kicker">Personal check</p><h1 tabindex="-1">Identify your machine.</h1><p class="muted">No QR or participating hirer needed. These details are recorded by you.</p><form id="personalForm"><label>Make / model<input name="model" placeholder="e.g. JCB 540-170" maxlength="80" required></label><label>Fleet number or serial<input name="fleet" maxlength="80" required></label><button class="primary">CONTINUE</button></form>${btn('Back','home','text-button')}`;}
if(page==='machine'){narrow=true;c=`<p class="kicker">01 / Confirm machine</p><h1 tabindex="-1">${esc(machine.name)}</h1><dl class="facts"><div><dt>Fleet number</dt><dd>${esc(machine.fleet)}</dd></div><div><dt>Permanent identity</dt><dd>${esc(machine.id||'Unverified personal entry')}</dd></div><div><dt>Hirer</dt><dd>${esc(machine.hirer||'Not connected')}</dd></div></dl><div class="status">${machine.hirer?`Copies of your completed checks will go to <strong>${esc(machine.hirer)}</strong>.`:'This is your personal record. No hirer receives it automatically.'}</div>${btn('THIS IS MY MACHINE','site')}${btn('Choose another machine','scan','text-button')}`;}
if(page==='site'){narrow=true;c=`<p class="kicker">02 / Site & copies</p><h1 tabindex="-1">Where are you working?</h1>${machine.id&&site!==machine.site?'<div class="status warn">Different site reported. The old recipient is cleared. The hirer’s placement stays unchanged until confirmed.</div>':''}<form id="siteForm"><label>Site name<input id="siteName" name="site" value="${esc(site)}" maxlength="100" required></label><label>Site email for a PDF copy <span class="muted small">Optional</span><input id="recipientEmail" name="recipient" type="email" value="${esc(recipient)}" placeholder="Address the manager gave you"></label><p class="field-note">Remembered for this site during this demo. Changing the site clears the previous recipient.</p><button class="primary">CONFIRM SITE & RECIPIENTS</button></form>${btn('Try moving to Cromwell Road','move','ghost')}${btn('Back','machine','text-button')}`;}
if(page==='ready'){narrow=true;c=`<p class="kicker">03 / Ready</p><h1 tabindex="-1">${esc(machine.fleet)}</h1><p class="muted lead">${esc(machine.name)} · ${esc(site)}</p>${recipients()}<p class="field-note">Short example checklist for reviewing the journey. Not an approved inspection checklist.</p>${btn('START EXAMPLE CHECK','start')}${btn('Change site or recipient','site','text-button')}`;}
if(page==='check'){narrow=true;const section=areas.slice(stage*3,stage*3+3);c=`<p class="kicker">${esc(machine.fleet)} · ${esc(site)}</p><div class="steps"><span class="done"></span><span class="${stage?'done':''}"></span></div><h1 tabindex="-1">${stage?'Cab & safety':'Walk around'}</h1><p class="muted small">Example checklist · ${stage+1} of 2</p>${section.map(a=>`<div class="question"><h3>${a}</h3><div class="choices" role="group" aria-label="${a}">${['OK','Defect','N/A'].map(v=>`<button type="button" data-answer="${a}" data-value="${v}" aria-pressed="${answers[a]===v}" class="${answers[a]===v?'selected ':''}${v==='Defect'?'defect':''}">${v}</button>`).join('')}</div></div>`).join('')}<div class="actions">${btn('Back',stage?'check-back':'ready','ghost')}${btn(stage?'REVIEW CHECK':'NEXT',stage?'review':'check-next')}</div>`;}
if(page==='review'){narrow=true;const defect=Object.values(answers).includes('Defect');c=`<p class="kicker">04 / Review</p><h1 tabindex="-1">${defect?'Record the defect.':'Check your record.'}</h1>${defect?'<div class="status warn">Defect reported. This demo does not clear a machine for use or alert anyone.</div>':''}<form id="completeForm"><label>${defect?'Describe the defect':'Notes (optional)'}<textarea name="note" maxlength="500" ${defect?'required':''}>${esc(note)}</textarea></label><label>Add example photo (optional)<input name="photo" id="photo" type="file" accept="image/*"></label><p class="field-note">Stays in this browser only. The PDF demo includes the photo filename, not the image.</p><div id="photoName" class="muted small">${esc(photo)}</div><div class="box">${areas.map(a=>`<div class="row"><span>${a}</span><strong>${esc(answers[a])}</strong></div>`).join('')}</div>${recipients()}<label class="inline-check"><input type="checkbox" required><span>I have reviewed this example record and its recipients.</span></label><button class="primary">${recipient?'COMPLETE & EMAIL PDF':'COMPLETE & SAVE'}</button><p class="field-note">Completion and email delivery are simulated. No real inspection is recorded.</p></form>${btn('Back to checklist','check','text-button')}`;}
if(page==='complete'){narrow=true;c=`<div class="checkmark">✓</div><p class="kicker">Demo record completed</p><h1 tabindex="-1">Your check is saved.</h1><p class="muted">Saved for this browser session only.</p><div class="status">${selected.recipient?`Email preview prepared for <strong>${esc(selected.recipient)}</strong>. No email sent.`:'No site recipient selected. Your record is available below.'}</div>${btn('VIEW RECORD & PDF','record:'+selected.id)}${selected.recipient?btn('Preview site email','email','ghost'):''}${btn('Back to home','home','text-button')}`;}
if(page==='records'){c=`<p class="kicker">Operator · ${esc(user.name)}</p><h1 tabindex="-1">My records.</h1><p class="muted">Your checks across sites. Completed details stay as recorded.</p>${rows(records)}${btn('Start another check','scan')}`;}
if(page==='record'&&selected){narrow=true;c=`<p class="kicker">${esc(selected.id)} · Demo record</p><h1 tabindex="-1" class="record-title">${esc(selected.name)}</h1><span class="badge ${selected.defect?'warn':''}">${selected.defect?'Defect reported':'No defects reported'}</span><dl class="facts">${[['Operator',selected.operator],['Completed',selected.time],['Machine',selected.fleet],['Site',selected.site],['Site PDF recipient',selected.recipient||'None'],['Hirer',selected.hirer||'Not connected']].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="box">${Object.entries(selected.answers).map(([a,v])=>`<div class="row"><span>${esc(a)}</span><strong>${esc(v)}</strong></div>`).join('')}<p class="muted">${esc(selected.note||'No notes.')}</p>${selected.photo?`<p class="small">Photo: ${esc(selected.photo)} (demo filename only)</p>`:''}</div>${btn('DOWNLOAD DEMO PDF','pdf')}${selected.recipient?btn('Preview site email','email','ghost'):''}${btn('Back',role==='hirer'?'fleet':'records','text-button')}`;}
if(page==='email'&&selected){narrow=true;c=`<p class="kicker">Email preview · Not sent</p><h1 tabindex="-1">Site copy.</h1><dl class="facts"><div><dt>To</dt><dd>${esc(selected.recipient)}</dd></div><div><dt>Subject</dt><dd>Machine check · ${esc(selected.fleet)} · ${esc(selected.site)}</dd></div></dl><div class="box"><p>A machine check was completed by ${esc(selected.operator)}.</p><p>${esc(selected.name)} · ${esc(selected.site)}</p><p><strong>${selected.defect?'Defect reported — review the record.':'No defects reported in this example check.'}</strong></p><p class="muted">Attachment: ${esc(selected.id)}.pdf</p></div><div class="status">Preview only. The site would receive the PDF without needing an account.</div>${btn('Back to record','record:'+selected.id)}`;}
if(page==='fleet'){const linked=records.filter(r=>r.hirer==='Northbank Plant Hire');c=`<p class="kicker">Hirer demo · Northbank Plant Hire</p><h1 tabindex="-1">Your machines.<br>Their latest checks.</h1><div class="stats"><div><strong>3</strong><span>Pilot machines</span></div><div><strong>${linked.length}</strong><span>Checks received in demo</span></div><div><strong>${linked.filter(r=>r.defect).length}</strong><span>Defect reports</span></div></div><div class="box"><div class="table-scroll"><table><thead><tr><th>Machine</th><th>Placement</th><th>Latest submission</th><th></th></tr></thead><tbody>${machines.map(m=>{const r=linked.find(r=>r.machineId===m.id);return `<tr><td><strong>${m.fleet}</strong><br><span class="muted">${m.name}</span></td><td>${m.site}${r&&r.site!==m.site?'<br><span class="badge warn">Site mismatch reported</span>':''}</td><td><span class="badge ${!r?'neutral':r.defect?'warn':''}">${!r?'No check received':r.defect?'Defect reported':'Check received'}</span></td><td>${btn('View','asset:'+m.id,'ghost')}</td></tr>`}).join('')}</tbody></table></div></div><p class="muted small">No check received does not mean the machine was not checked. Placements are example hirer records, not GPS locations.</p>${linked.length?`<h2>Recent submissions</h2>${rows(linked.slice(0,5))}`:''}`;}
if(page==='asset'){const list=records.filter(r=>r.machineId===machine.id);c=`<p class="kicker">Northbank Plant Hire · Fleet detail</p><h1 tabindex="-1">${machine.fleet}</h1><p class="muted">${machine.name}</p><div class="grid"><div class="box"><h2>Recorded placement</h2><p>${machine.site}</p><p class="muted small">An operator’s different-site report does not change this placement.</p><dl class="facts"><div><dt>Permanent identity</dt><dd>${machine.id}</dd></div></dl>${btn('Try operator scan for this machine','try:'+machine.id,'ghost')}</div><div><h2>Inspection history</h2>${rows(list)}</div></div>${btn('Back to fleet','fleet','text-button')}`;}
root.innerHTML=shell(c,narrow)+`<div class="wrap narrow" style="padding-top:0;padding-bottom:20px"><p class="error" role="alert">${esc(error)}</p></div>`;
root.querySelector('#siteName')?.addEventListener('input',()=>{root.querySelector('#recipientEmail').value='';});
root.querySelector('#photo')?.addEventListener('change',e=>{photo=e.target.files[0]?.name||'';root.querySelector('#photoName').textContent=photo;});
}
function selectMachine(id){machine=machines.find(m=>m.id===id);site=machine.site;recipient=destinations[site]||'';go('machine');}
root.addEventListener('click',e=>{const choice=e.target.closest('[data-answer]');if(choice){answers[choice.dataset.answer]=choice.dataset.value;render();return;}const b=e.target.closest('[data-action]');if(!b)return;e.preventDefault();const a=b.dataset.action;
if(a==='signup'){signup=!signup;go('login');return;}if(a==='demo-user'){user={name:'Operator K',email:'operator.k@example.com'};role='operator';go('home');return;}if(a==='switch'){if(!user)user={name:'Operator K',email:'operator.k@example.com'};role=role==='hirer'?'operator':'hirer';go(role==='hirer'?'fleet':'home');return;}if(a==='logout'){user=null;go('login');return;}if(a==='home'){go(user?(role==='hirer'?'fleet':'home'):'login');return;}if(a==='verify'){go('home');return;}if(a.startsWith('machine:')){selectMachine(a.split(':')[1]);return;}if(a.startsWith('try:')){role='operator';selectMachine(a.split(':')[1]);return;}if(a.startsWith('asset:')){machine=machines.find(m=>m.id===a.split(':')[1]);go('asset');return;}if(a.startsWith('record:')){selected=records.find(r=>r.id===a.split(':')[1]);go('record');return;}if(a==='move'){site=site==='Cromwell Road'?'Whitmore Road':'Cromwell Road';recipient='';go('site');return;}if(a==='start'){answers={};note='';photo='';stage=0;go('check');return;}if(a==='check-back'){stage=0;go('check');return;}if(a==='check-next'||a==='review'){if(areas.slice(stage*3,stage*3+3).some(k=>!answers[k])){error='Choose OK, Defect or N/A for each item.';render();return;}if(a==='check-next'){stage=1;go('check');}else go('review');return;}if(a==='pdf'){downloadPDF(selected);return;}go(a);
});
root.addEventListener('submit',e=>{e.preventDefault();const f=e.target,d=new FormData(f);if(f.id==='loginForm'){email=d.get('email').trim();user={email,name:d.get('name')?.trim()||'Operator K'};role='operator';go('verify');}if(f.id==='codeForm'){if(d.get('code')!=='123456'){error='For this demo, enter 123456.';render();}else go('home');}if(f.id==='personalForm'){machine={id:null,name:d.get('model').trim(),fleet:d.get('fleet').trim(),hirer:null,site:''};site='';recipient='';go('machine');}if(f.id==='siteForm'){site=d.get('site').trim();if(!site){error='Enter a site name.';render();return;}recipient=d.get('recipient').trim();destinations[site]=recipient;go('ready');}if(f.id==='completeForm'){note=d.get('note').trim();const defect=Object.values(answers).includes('Defect');if(defect&&!note){error='Describe the reported defect before completing.';render();return;}selected={id:'DEMO-'+String(records.length+1).padStart(4,'0'),machineId:machine.id,name:machine.name,fleet:machine.fleet,hirer:machine.hirer,site,recipient,operator:user.name,email:user.email,time:new Date().toLocaleString('en-GB'),answers:{...answers},note,photo,defect};records.unshift(selected);go('complete');}});
function downloadPDF(r){const clean=s=>String(s).replace(/[^\x20-\x7e]/g,' ').replace(/[\\()]/g,'\\$&');const lines=['MACHINE PRE-CHECK','DEMO RECORD - NOT A REAL INSPECTION',r.id,r.name+' / '+r.fleet,'Operator: '+r.operator,'Completed: '+r.time,'Site: '+r.site,'Site copy: '+(r.recipient||'None'),'Hirer: '+(r.hirer||'Not connected'),''];Object.entries(r.answers).forEach(([k,v])=>lines.push(k+': '+v));lines.push('','Notes:');(r.note||'None').match(/.{1,75}/g)?.forEach(l=>lines.push(l));lines.push('Photo filename: '+(r.photo||'None'),'No email was sent. Example checklist only.');const stream='BT /F1 11 Tf 48 790 Td 17 TL '+lines.map((l,i)=>(i?'T* ':'')+'('+clean(l)+') Tj').join('\n')+' ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream'];let pdf='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(pdf.length);pdf+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});let x=pdf.length;pdf+='xref\n0 6\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n'+x+'\n%%EOF';const url=URL.createObjectURL(new Blob([pdf],{type:'application/pdf'})),a=document.createElement('a');a.href=url;a.download=r.id+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
render();
})();
